[build]
  publish = "_site"
  command = "npm run build"

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 3000
  publish = "_site"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404